### PR TITLE
SwiftPM support & API Improvements

### PR DESCRIPTION
**Pull request by maximkrouk**
> API changes are compatible with `0.1.0` but significant enough to be `0.2.0`, so I increased the versions in Readme and Podspec

### CODE REVIEW

**Comment by MarioIannotta** [comment]
Thanks a lot for this PR! Everything looks very good.
I just have a couple of thoughts on the `avoidScreenshots()` API.

Since the view will also *avoid recordings*, I think the name is a bit misleading.
Furthermore, I recently discovered the [privacySensitive(_:)](https://developer.apple.com/documentation/swiftui/angulargradient/privacysensitive(_:)#) api (unfortunately it is available only on SwiftUI and iOS 15.)

I don't like it too munch but maybe we can use the same naming? What do you think?

**Comment by rursache** [comment]
@MarioIannotta can you merge this? SPM support is needed in 2023. thanks!

**Comment by maximkrouk** [comment]
@MarioIannotta 
Didn't get a notification for your comment from 13.05.2022 😅
I'll push an update tomorrow, I think it'll be nice to have an API similar to the standard one

**Comment by maximkrouk** [comment]
Sorry for the delay, here is an update :)

**Comment by MarioIannotta** [comment]
Thanks a lot! Merged 👍

**Pull request merged**
